config/routes.rb
Rails.application.routes.draw do

  root 'snippets#index'

  resources :users
  get "/secret-snippets" => "snippets#secret_snippets", as: :secret_snippets
  resources :snippets
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    can :manage, Snippet do |snippet|
      snippet.user == user
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  after_initialize :set_defaults
  belongs_to :user
  KIND_RUBY         = "Ruby"
  KIND_HTML         = "HTML"
  KIND_CSS          = "CSS"
  KIND_JAVASCRIPT   = "JavaScript"
  KINDS = [KIND_RUBY, KIND_HTML, KIND_CSS, KIND_JAVASCRIPT]

  validates :kind, presence: true, inclusion: { in: KINDS }
  validates :title, presence: true, uniqueness: true
  validates :code, presence: true

  scope :recent, ->( number = 5){ order("created_at DESC").limit(number) }
  scope :public_snippet, -> {where({private: false})}
  scope :private_snippet, -> {where({private: true})}

   def set_defaults
    self.kind ||= KIND_RUBY
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :snippets, dependent: :destroy

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # temporarily store password in memory
  # attr_accessor :password
  # attr_accessor :password_confirmation
  # add ^^ attributes for us.
  has_secure_password
  validates :password, length: { minimum: 5 }, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
            uniqueness: true,
            format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}".titleize.strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||=  User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def sign_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in :) " unless user_signed_in?
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def create
     user = User.find_by(email: params[:session][:email])
     if user && user.authenticate(params[:session][:password])
       sign_in(user)
       redirect_to root_path, flash: {success: "Signed in!" }
     else
       flash[:warning] = "Invalid email/password combination"
       render :new
     end
   end

   def destroy
     session[:user_id] = nil
     redirect_to root_path, flash: {danger: "Logged Out"}
   end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
#     if user_signed_in?
#       # @snippets = current_user.snippets.where("private = ? AND private = ?", true, false).joins(Snippet.public_snippet.order("created_at DESC"))
#       @snippets = Snippet.where("private = ? AND #{current_user.snippets} = ?", false, true)
#       # @snippets = Snippet.where(["private = ? OR #{current_user.snippets.private_snippet} = ?", false, true ])
# # @snippets = (Snippet.public_snippet.order("created_at DESC") + current_user.snippets.private_snippet.order("created_at DESC"))
#     else
  # @snippets = Snippet.where(["private = ? OR #{current_user.snippets.private_snippet} = ?", false, true])
      @snippets = Snippet.public_snippet.order("created_at DESC")
    # end
  end

  def secret_snippets
    @snippets = current_user.snippets.private_snippet.order("created_at DESC")
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    @snippet.user = current_user
      if @snippet.save
        redirect_to snippets_path(@snippet), flash: { success: "Snipped!"}
      else
        flash[:danger] = "Snippet Failure ..."
        render :new
      end
  end

  def show
  end

  def edit
  end

  def update
    if @snippet.update(snippet_params)
      redirect_to(snippet_path(@snippet), flash: { success:  "Snippet Updated"})
    else
      flash[:warning] = "Snippet was not successful"
      render :edit
    end
  end

  def destroy
    snippet = current_user.snippets.find(params[:id])
    snippet.destroy
    redirect_to((root_path), flash: { danger: "Snippet Removed!" })
  end

  private

    def snippet_params
      params.require(:snippet).permit([:kind, :title, :code, :private])
    end

    def find_snippet
      @snippet = Snippet.find(params[:id])
    end

    def authorize_user
      unless can? :manage, @snippet
      redirect_to root_path , flash: { info: "Access Denied" }
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # session simply checks for the user.ID in the current session?
      # session[:user_id] = @user.id
      sign_in(@user)
      redirect_to(root_path, flash: { success: "User Created!"})
    else
      flash[:warning] = "Invalid Attribrutes"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, flash: {success: "Information Renewed..."}
    else
      render :edit
    end
  end

  def destroy
  end

    private

      def user_params
        params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
      end

      def find_user
        @user = User.find(params[:id])
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end
  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def html_kind(kind)
     k = kind.downcase

     case k
     when "ruby"
       {color: "panel-ruby", icon: fa_icon('diamond'), text: "Ruby" }
     when "html"
       {color: "panel-html", icon: fa_icon('html5'), text: "HTML" }
     when "javascript"
       {color: "panel-javascript", icon: fa_icon("coffee"), text: "JavaScript" }
     when "css"
       {color: "panel-css", icon: fa_icon('css3'), text: "CSS" }
     else
       {color: "panel-default", icon: ""}
     end

   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash %>
  <section class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-lg-center">
        <% flash.each do | message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end  %>
      </div>
    </div>
  </section>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-full navbar-dark" style = "background-color: #f1404b">
  <div class="container">
    <%= link_to fa_icon("code-fork"), root_path, class: "code-logo fa-3x" %>
    <%= link_to fa_icon("cogs"), root_path, class: "code-logo fa-3x" %>
    <%# link_to fa_icon("cogs"), root_path, class: "code-logo fa-3x" %>
    <%# link_to fa_icon("code-fork"), root_path, class: "code-logo fa-3x" %>

  <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2"> &#9776; </button>
  <div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">
          <strong><%= link_to "<code></snippets>", root_path, class: "text-lg-center nav-link brand-homepage" %></strong>
        <li class="nav-item <%# 'active' if current_page?(new_question_path) %>">
          <%# link_to "Ask a Question", new_question_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(sessions_path) %>">
          <%= link_to "log out", sessions_path, method: :delete, class: "nav-link" %>
          <li class="nav-item <%= 'active' if current_page?(edit_user_path(current_user)) %>">
            <%= link_to "edit profile", edit_user_path(current_user), class: "nav-link" %>
          </li>

          <li class="nav-item <%= 'active' if current_page?(edit_user_path(current_user)) %>">
            <%= link_to "create snippet", new_snippet_path, class: "nav-link" %>
          </li>
        <li class="nav-item <%= 'active' if current_page?(secret_snippets_path) %>">
          <%= link_to "secret snippets", secret_snippets_path, class: "nav-link" %>
        </li>



        </li>
        <% else %>
        <li class="nav-item <%= 'active' if current_page?(new_user_path) %>">
          <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
          <%= link_to "Sign In", new_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/flash" %>
  <main class="container">
    <%= yield %>
  </main>
</body>
</html>

app/views/snippets/_snippet_form.html.erb
<% if @snippet.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
  <ul>
    <% @snippet.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @snippet do |f| %>
    <div class = "form-group">
    <%= f.label :kind %>
    <%= f.select :kind, [
             ["#{Snippet::KIND_RUBY}","#{Snippet::KIND_RUBY}"],
             ["#{Snippet::KIND_HTML}","#{Snippet::KIND_HTML}"],
             ["#{Snippet::KIND_CSS}","#{Snippet::KIND_CSS}"],
             ["#{Snippet::KIND_JAVASCRIPT}","#{Snippet::KIND_JAVASCRIPT}"]
           ], {}, {class: "form-control"} %>
    </div>
    <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class = "form-group">
    <%= f.label :code %>
    <%= f.text_area :code, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :private do %>
      <%= f.check_box :private, class: "checkbox-inline" %>
      <span>Make Snippet Private?</span>
      <% end %>
    </div>
    <div class = "form-group">
    <%= f.submit "Post the Snippet", class: "btn btn-success-outline btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/snippets/edit.html.erb
<h1 class = "text-lg-center title">Edit Your Code Snippet</h1>
<%= render "snippet_form" %>

app/views/snippets/index.html.erb
<h1 class = "title text-lg-center all-public-snippets">All Public Snippets (<%= @snippets.length %>)</h1>

<!-- <div class="col-md-10 col-md-offset-1"> -->
<div class="row">
  <nav class="code-navigation col-md-10 col-md-offset-1">
    <ul class="nav nav-pills text-lg-center" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#ruby" role="tab">Ruby
        <%= fa_icon('diamond') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#html" role="tab">HTML <%= fa_icon('html5')  %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#css" role="tab">CSS  <%= fa_icon('css3') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#javascript" role="tab">JavaScript <%= fa_icon("coffee") %></a>
      </li>
    </ul>
  </nav>
</div>

<!-- Tab panes -->
<% if @snippets %>
<div class="tab-content snippets-listing row">
  <div class="tab-pane active col-md-6 col-md-offset-3" id="ruby" role="tabpanel">
    <% @snippets.where({kind: "Ruby"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="html" role="tabpanel">
    <% @snippets.where({kind: "HTML"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="css" role="tabpanel">
    <% @snippets.where({kind: "CSS"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="javascript" role="tabpanel">
    <% @snippets.where({kind: "JavaScript"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
</div>
<% end %>





    <!-- <table class="table table-striped"> -->
      <%# @snippets.each do |snippet| %>
        <!-- <tr> -->
          <!-- <td><%# link_to snippet.title, snippet_path(snippet) %></td> -->
        <!-- </tr> -->
      <%# end %>
    <!-- </table> -->

app/views/snippets/new.html.erb
<h1 class = "text-lg-center title">Add a Code Snippet</h1>
<% if @snippet.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
  <ul>
    <% @snippet.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @snippet do |f| %>
    <div class = "form-group">
    <%= f.label :kind %>
    <%= f.select :kind, [
             ["#{Snippet::KIND_RUBY}","#{Snippet::KIND_RUBY}"],
             ["#{Snippet::KIND_HTML}","#{Snippet::KIND_HTML}"],
             ["#{Snippet::KIND_CSS}","#{Snippet::KIND_CSS}"],
             ["#{Snippet::KIND_JAVASCRIPT}","#{Snippet::KIND_JAVASCRIPT}"]
           ], {}, {class: "form-control"} %>
    </div>
    <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class = "form-group create-code">
    <%= f.label :code %>
    <%= f.text_area :code, class: "form-control", style: "height: 250px; font-family: monospace;font-size:13px "%>
    </div>
    <div class="form-group">
      <%= f.label :private do %>
      <%= f.check_box :private, class: "checkbox-inline" %>
      <span>Secret Snippet?</span>
      <% end %>
    </div>
    <div class = "form-group">
    <%= f.submit "Post the Snippet", class: "btn btn-success-outline btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/snippets/secret_snippets.html.erb
<h1 class = "title text-lg-center">Secret Snippets (<%= @snippets.length %>)</h1>

<!-- <div class="col-md-10 col-md-offset-1"> -->
<div class="row">
  <nav class="code-navigation col-md-10 col-md-offset-1">
    <ul class="nav nav-pills text-lg-center" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#ruby" role="tab">Ruby
        <%= fa_icon('diamond') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#html" role="tab">HTML <%= fa_icon('html5')  %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#css" role="tab">CSS  <%= fa_icon('css3') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#javascript" role="tab">JavaScript </a>
      </li>
    </ul>
  </nav>
</div>
<% if @snippets %>
<div class="tab-content row">
  <div class="tab-pane active col-md-6 col-md-offset-3" id="ruby" role="tabpanel">
    <% @snippets.where({kind: "Ruby"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="html" role="tabpanel">
    <% @snippets.where({kind: "HTML"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="css" role="tabpanel">
    <% @snippets.where({kind: "CSS"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
  <div class="tab-pane col-md-6 col-md-offset-3" id="javascript" role="tabpanel">
    <% @snippets.where({kind: "JavaScript"}).each do |snippet| %>
       <div class="panel-heading striped-panel">
         <%= link_to "#{snippet.title}", snippet_path(snippet)  %>
         <span class="pull-right">
          <%= html_kind(snippet.kind)[:icon]%>
         </span>
       </div>
    <% end %>

  </div>
</div>
<% end %>

app/views/snippets/show.html.erb
<div class="row">
  <div class="snippet-display form-group-lg col-md-8 col-md-offset-2">
      <h1 class = "snippet-<%= @snippet.kind %>"><%= @snippet.title %>
        <%= html_kind(@snippet.kind)[:icon]%>
       </h1>
      <%# raw(Pygments.highlight(@snippet.code, lexer: @snippet.kind)) %>
      <%= markdown(@snippet.code)   %>
      <% if can? :manage, @snippet %>
      <p><%= link_to "EDIT", edit_snippet_path(@snippet), class: "text-muted" %> <%= link_to "DELETE", snippet_path(@snippet), method: :delete, data: { confirm: "Are you sure??"}, class: "text-muted" %></p>
      <% end %>
  </div>
</div>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@user.errors.count, "error") %></strong>.</p>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
</div>
<% end %>

<div class="row">
<div class="form-group-lg col-md-6 col-md-offset-3">
<%= form_for @user do |f| %>
  <div class = "form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
<div class = "form-group">
    <%= f.label :email  %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :password  %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.submit "Create Account", class: "btn btn-primary-outline btn-block" %>
  </div>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h3 class = "title text-lg-center"><%= @user.first_name %>, use this page to edit your information.</h1>
<%= render "user_form" %>

app/views/users/new.html.erb
<h1 class = "text-lg-center title">Sign Up</h1>
<%= render "user_form" %>